WITH GROUP_TABLE AS (
    SELECT
        ROUTE,
        ROUND(SUM(D_BETWEEN_DIST), 1) AS T_DIST,
        ROUND(AVG(D_BETWEEN_DIST), 2) AS A_DIST
    FROM
        SUBWAY_DISTANCE
    GROUP BY
        ROUTE
)

SELECT
    ROUTE,
    CONCAT(T_DIST, 'km') AS TOTAL_DISTANCE,
    CONCAT(A_DIST, 'km') AS AVERAGE_DISTANCE
FROM
    GROUP_TABLE
ORDER BY
    T_DIST DESC
;