-- 코드를 입력하세요
SET @USER_COUNT = (
    SELECT
        COUNT(*)
    FROM
        USER_INFO
    WHERE
        YEAR(JOINED) = 2021
);

SELECT
    YEAR(O.SALES_DATE) AS YEAR,
    MONTH(O.SALES_DATE) AS MONTH,
    COUNT(DISTINCT O.USER_ID) AS PUCHASED_USERS,
    ROUND(COUNT(DISTINCT O.USER_ID) / @USER_COUNT, 1) AS PUCHASED_RATIO
FROM
    ONLINE_SALE AS O
INNER JOIN
    USER_INFO AS U ON O.USER_ID = U.USER_ID
WHERE
    YEAR(U.JOINED) = 2021
GROUP BY
    YEAR,
    MONTH
ORDER BY
    YEAR ASC,
    MONTH ASC
;