-- 코드를 입력하세요
WITH RECURSIVE HOURS_TABLE AS (
    SELECT 0 AS HOUR_VALUE
    UNION ALL
    SELECT HOUR_VALUE + 1 FROM HOURS_TABLE WHERE HOUR_VALUE < 23
)

SELECT
    H.HOUR_VALUE AS HOUR,
    COUNT(A.ANIMAL_ID) AS COUNT
FROM
    HOURS_TABLE AS H
LEFT JOIN
    ANIMAL_OUTS AS A
ON
    H.HOUR_VALUE = HOUR(A.DATETIME)
GROUP BY
    HOUR
ORDER BY
    HOUR ASC
;