-- 코드를 입력하세요
WITH T AS (
    SELECT
        CAR_ID,
        COUNT(*) AS RENTAL_COUNT
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY
        CAR_ID
    HAVING
        RENTAL_COUNT >= 5
)

SELECT
    MONTH(H.START_DATE) AS MONTH,
    H.CAR_ID,
    COUNT(*) AS RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H,
    T
WHERE
    H.CAR_ID = T.CAR_ID
AND
    H.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY
    MONTH,
    H.CAR_ID
ORDER BY
    MONTH ASC,
    H.CAR_ID DESC
;