-- 코드를 입력하세요
WITH M AS (
    SELECT
        CATEGORY,
        MAX(PRICE) AS MAX_PRICE
    FROM
        FOOD_PRODUCT
    WHERE
        CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY
        CATEGORY
)
SELECT
    FOOD_PRODUCT.CATEGORY,
    FOOD_PRODUCT.PRICE AS MAX_PRICE,
    FOOD_PRODUCT.PRODUCT_NAME
FROM
    FOOD_PRODUCT,
    M
WHERE
    FOOD_PRODUCT.CATEGORY = M.CATEGORY
AND
    FOOD_PRODUCT.PRICE = M.MAX_PRICE
ORDER BY
    MAX_PRICE DESC
;